imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

#doctrine_mongodb:
#    document_managers:
#        default:
#            auto_mapping: true
#            metadata_cache_driver: array

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
