parameters:
    distFiles:
        js:
            - jquery/dist/jquery.min.js
            - jquery/dist/jquery.min.map
            - angular/angular.min.js
            - angular/angular.min.js.map
            - bootstrap/dist/js/bootstrap.min.js
            - angular-cookies/angular-cookies.min.js
            - angular-cookies/angular-cookies.min.js.map
            - angular-ui-router/release/angular-ui-router.min.js
        css:
            - bootstrap/dist/css/bootstrap.min.css
            - bootstrap/dist/css/bootstrap.min.css.map
        fonts:
            - bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            - bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            - bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            - bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            - bootstrap/dist/fonts/glyphicons-halflings-regular.woff2